## Numpy

In [1]:
import numpy as np

In [2]:
array = np.random.randint(1,1000,50) #1부터 10000까지 50개의 데이터를 랜덤하게 추출

In [3]:
array

array([473, 558, 473, 249,  54, 383, 900, 236, 308, 535, 953, 667,  90,
       524, 863, 446, 286, 257, 944, 325, 282, 314, 192, 198, 100, 947,
       763, 993, 290, 408, 998, 780, 650,  11, 351, 251, 618, 682, 523,
       464,  85,  84, 455, 536, 621, 438, 810, 753, 232,   8])

In [4]:
np.mean(array) #평균 구하기

467.22

In [5]:
array > np.mean(array)

array([ True,  True,  True, False, False, False,  True, False, False,
        True,  True,  True, False,  True,  True, False, False, False,
        True, False, False, False, False, False, False,  True,  True,
        True, False, False,  True,  True,  True, False, False, False,
        True,  True,  True, False, False, False, False,  True,  True,
       False,  True,  True, False, False])

In [7]:
array[array > np.mean(array)].size #True인 값만 뽑은 후 개수 세기

23

In [8]:
## 300보다 작은 원소의 개수
array[array < 300].size

17

## Pandas

In [9]:
import pandas as pd
import numpy as np

In [15]:
s1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10])

In [17]:
s1.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
s1.index

RangeIndex(start=0, stop=10, step=1)

In [18]:
s2 = pd.Series([1,2,3], index=['one','two','three'])

In [19]:
s2

one      1
two      2
three    3
dtype: int64

In [22]:
print(s2.std()) # 편차
print(s2.sum()) # 합
print(s2.mean()) # 평균

1.0
6
2.0


In [23]:
pd.Series({1:1,2:2,3:3})

1    1
2    2
3    3
dtype: int64

In [26]:
s2 = pd.Series({'one':[1,2,3],'two':[2,3,5]})

In [28]:
s2.values

array([list([1, 2, 3]), list([2, 3, 5])], dtype=object)

## Titanic

In [30]:
titanic_df = pd.read_csv('titanic_train.csv', encoding='cp949')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [31]:
titanic_df.index

RangeIndex(start=0, stop=891, step=1)

In [32]:
titanic_df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [36]:
titanic_df.PassengerId.values

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [39]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [40]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [43]:
print(titanic_df.describe()) #집계함수
print(titanic_df.describe().PassengerId['25%'])

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  
223.5


In [44]:
titanic_df.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [45]:
titanic_df.Age.isna() ## NaN이면 True

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [47]:
titanic_df.Age.fillna(0, inplace=True) ## NaN에 값 채우기, inplace : 원래의 값 바꾸기

In [48]:
## 새 column 추가하기
titanic_df['Age_class'] = 0
titanic_df.Age_class

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Age_class, Length: 891, dtype: int64

In [49]:
## column 지우기
titanic_df.drop('Age_class',axis=1,inplace=True)

In [52]:
# 나이에 따른 클래스 생성하기
# 생성조건
# 1. 6세 이하는 2
# 2. 6~35세는 1
# 3. 35세 이상은 0
# 원본 데이터에 생성한 클래스를 컬럼으로 추가

Age_class = []

for Age in titanic_df.Age:
    if Age < 6:
        tmp = 2
    elif Age < 35:
        tmp = 1
    else:
        tmp = 0
    Age_class.append(tmp) ## 클래스에 tmp값 추가
    
# 원본 데이터에 생성한 클래스를 컬럼으로 추가
titanic_df['Age_class'] = Age_class

In [54]:
titanic_df[['Age','Age_class']]

Age  Age_class
0    22.0          1
1    38.0          0
2    26.0          1
3    35.0          0
4    35.0          0
..    ...        ...
886  27.0          1
887  19.0          1
888   0.0          2
889  26.0          1
890  32.0          1

[891 rows x 2 columns]

In [56]:
titanic_df.Age_class.value_counts()

1    435
0    235
2    221
Name: Age_class, dtype: int64

In [58]:
# numpy의 where(condition, True, False) : 
np.where([False, False, True, True, False], "x", "y")

array(['y', 'y', 'x', 'x', 'y'], dtype='<U1')

In [60]:
titanic_df['Age_class_n'] = np.where(titanic_df.Age < 6, 2, np.where(titanic_df.Age < 35, 1, 0))

In [61]:
titanic_df[['Age','Age_class','Age_class_n']]

Age  Age_class  Age_class_n
0    22.0          1            1
1    38.0          0            0
2    26.0          1            1
3    35.0          0            0
4    35.0          0            0
..    ...        ...          ...
886  27.0          1            1
887  19.0          1            1
888   0.0          2            2
889  26.0          1            1
890  32.0          1            1

[891 rows x 3 columns]

In [66]:
## 데이터 가져오기
titanic_df['PassengerId'] ## 1개의 컬럼은 Series
titanic_df[['PassengerId','Age']] ## 여러개의 컬럼 가져오기
titanic_df[0:3] # 슬라이싱 : row 가져옴
titanic_df[titanic_df.Age_class==1] ## boolean을 이용하여 row 추출
titanic_df[titanic_df.Age_class==1][['Survived','Name','Age']]

Survived                                               Name   Age
0           0                            Braund, Mr. Owen Harris  22.0
2           1                             Heikkinen, Miss. Laina  26.0
8           1  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9           1                Nasser, Mrs. Nicholas (Adele Achem)  14.0
12          0                     Saundercock, Mr. William Henry  20.0
..        ...                                                ...   ...
884         0                             Sutehall, Mr. Henry Jr  25.0
886         0                              Montvila, Rev. Juozas  27.0
887         1                       Graham, Miss. Margaret Edith  19.0
889         1                              Behr, Mr. Karl Howell  26.0
890         0                                Dooley, Mr. Patrick  32.0

[435 rows x 3 columns]

In [70]:
## iloc
titanic_df.iloc[0:4,0:4]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name  
0                            Braund, Mr. Owen Harris  
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                             Heikkinen, Miss. Laina  
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [75]:
# 데이터 전처리를 위해 cabin 컬럼 삭제
titanic_df_column = titanic_df.drop('Cabin', axis=1)

# Embarked가 NaN인 row 삭제
titanic_df_column.Embarked.isna()
titanic_df_row = titanic_df_column.iloc[~np.array(titanic_df_column.Embarked.isna()),:]

In [76]:
titanic_df_row.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                   

In [80]:
titanic_df_row.reset_index(inplace=True)

In [81]:
titanic_df_row

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
884    886          887         0       2   
885    887          888         1       1   
886    888          889         0       3   
887    889          890         1       1   
888    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
884                              Montvila, Rev. Juozas    male  27.0      0   
885                       Graham, Miss. Margaret Edith  female  19.0      0   
886           Johnston, Miss. Catherine Helen "Carrie"  female   0.0      1   
887                              Behr, Mr. Karl Howell    male  26.0      0   
888                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Embarked  Age_class  Age_class_n  
0        0         A/5 21171   7.2500        S          1            1  
1        0          PC 17599  71.2833        C          0            0  
2        0  STON/O2. 3101282   7.9250        S          1            1  
3        0            113803  53.1000        S          0            0  
4        0            373450   8.0500        S          0            0  
..     ...               ...      ...      ...        ...          ...  
884      0            211536  13.0000        S          1            1  
885      0            112053  30.0000        S          1            1  
886      2        W./C. 6607  23.4500        S          2            2  
887      0            111369  30.0000        C          1            1  
888      0            370376   7.7500        Q          1            1  

[889 rows x 14 columns]

In [98]:
## 컬럼 선택
feature_cols = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Survived']
tiny_df = titanic_df_row[feature_cols]

In [99]:
tiny_df

Pclass     Sex   Age  SibSp  Parch  Survived
0         3    male  22.0      1      0         0
1         1  female  38.0      1      0         1
2         3  female  26.0      0      0         1
3         1  female  35.0      1      0         1
4         3    male  35.0      0      0         0
..      ...     ...   ...    ...    ...       ...
884       2    male  27.0      0      0         0
885       1  female  19.0      0      0         1
886       3  female   0.0      1      2         0
887       1    male  26.0      0      0         1
888       3    male  32.0      0      0         0

[889 rows x 6 columns]

In [100]:
## 성별을 정수로 바꾸기
#####copy warning######
tinytiny_df = tiny_df.copy()
tinytiny_df.Sex = np.where(tinytiny_df.Sex=='male', 0, 1)

In [102]:
tinytiny_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    889 non-null    int64  
 1   Sex       889 non-null    int64  
 2   Age       889 non-null    float64
 3   SibSp     889 non-null    int64  
 4   Parch     889 non-null    int64  
 5   Survived  889 non-null    int64  
dtypes: float64(1), int64(5)
memory usage: 41.8 KB


In [104]:
# 데이터 타입 바꾸기
tinytiny_df = tinytiny_df.astype('int32')

In [105]:
tinytiny_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Pclass    889 non-null    int32
 1   Sex       889 non-null    int32
 2   Age       889 non-null    int32
 3   SibSp     889 non-null    int32
 4   Parch     889 non-null    int32
 5   Survived  889 non-null    int32
dtypes: int32(6)
memory usage: 21.0 KB


In [106]:
tinytiny_df.head()

Pclass  Sex  Age  SibSp  Parch  Survived
0       3    0   22      1      0         0
1       1    1   38      1      0         1
2       3    1   26      0      0         1
3       1    1   35      1      0         1
4       3    0   35      0      0         0