## 데이터 전처리

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
raw_df = pd.read_csv("iris.csv") # encoding = 'cp949' | 'utf-8'

### 데이터 모양 확인 후 전처리 해야 할 것 확인

In [4]:
raw_df.info() # Non-Null이 150이 되도록 바꿈 / Dytpe을 동일하게 변경 / 첫번째에 있는 Unnamed 삭제

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Unnamed: 0         150 non-null    int64  
 1   sepal length (cm)  150 non-null    float64
 2   sepal width (cm)   150 non-null    float64
 3   petal length (cm)  150 non-null    float64
 4   petal width (cm)   150 non-null    float64
 5   Species            150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [9]:
raw_df.head()

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0           0                5.1               3.5                1.4   
1           1                4.9               3.0                1.4   
2           2                4.7               3.2                1.3   
3           3                4.6               3.1                1.5   
4           4                5.0               3.6                1.4   

   petal width (cm) Species  
0               0.2  setosa  
1               0.2  setosa  
2               0.2  setosa  
3               0.2  setosa  
4               0.2  setosa

In [14]:
#df.loc[행, 열] : 행 -> boolean 가능 / 열 -> column name
#df.iloc[인덱스 범위]

cl_df = raw_df.iloc[:,1:]
cl_df.info() # Species가 object 이므로 int 형으로 바꿔야 함

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Species            150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


## 종속변수

In [18]:
cl_df.Species.unique()
cl_df['label'] = np.where(cl_df.Species=='setosa',0,np.where(cl_df.Species=='versicolor',1,2))

In [19]:
from sklearn.preprocessing import LabelEncoder #라벨링 = np.where

In [21]:
label = LabelEncoder()
label.fit(cl_df.Species)
labels = label.transform(cl_df.Species)

In [22]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [23]:
cl_df['labels'] = labels

In [26]:
cl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Species            150 non-null    object 
 5   label              150 non-null    int64  
 6   labels             150 non-null    int64  
dtypes: float64(4), int64(2), object(1)
memory usage: 8.3+ KB


### train_set과 test_set 분리

In [25]:
X = cl_df.iloc[:,0:4]
y = cl_df.iloc[:,-1]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 전체 데이터의 30퍼를 test 데이터로 만듦, 랜덤으로 섞음

In [28]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
58                 6.6               2.9                4.6               1.3
98                 5.1               2.5                3.0               1.1
102                7.1               3.0                5.9               2.1
87                 6.3               2.3                4.4               1.3
12                 4.8               3.0                1.4               0.1
..                 ...               ...                ...               ...
72                 6.3               2.5                4.9               1.5
78                 6.0               2.9                4.5               1.5
131                7.9               3.8                6.4               2.0
96                 5.7               2.9                4.2               1.3
80                 5.5               2.4                3.8               1.1

[105 rows x 4 columns]

# 모델 만들기
- 모델 인스턴스 생성
- 모델에 데이터 학습
- 테스트 데이터로 예측값 구하기
- 모델의 성능(예측 결과)
- 새로운 데이터로 예측

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [31]:
tree_model = DecisionTreeClassifier()

In [32]:
tree_model.fit(X_train,y_train)

DecisionTreeClassifier()

In [33]:
result = tree_model.predict(X_test)

In [34]:
y_test

118    1
54     2
16     0
108    1
148    1
42     0
69     2
68     2
23     0
0      0
18     0
115    1
71     2
90     2
121    1
17     0
46     0
33     0
105    1
41     0
57     2
30     0
91     2
92     2
139    1
138    1
51     2
133    1
32     0
77     2
10     0
110    1
132    1
5      0
134    1
123    1
106    1
3      0
119    1
19     0
81     2
55     2
73     2
1      0
8      0
Name: labels, dtype: int64

In [35]:
result

array([1, 2, 0, 1, 1, 0, 2, 2, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 1, 0, 2, 0,
       2, 2, 1, 2, 2, 2, 0, 1, 0, 1, 1, 0, 1, 1, 2, 0, 2, 0, 2, 2, 2, 0,
       0])

In [36]:
sum(np.array(y_test)==result)/result.size # accuracy

0.8888888888888888

In [37]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy_score(result, y_test) # result 와 y_test를 비교하여 정확도 계산

0.8888888888888888

### SVM 모델

In [40]:
svm_model = SVC()
svm_model.fit(X_train, y_train)
result = svm_model.predict(X_test)
accuracy_score(result, y_test)

0.8888888888888888

In [42]:
cl_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       Species  label  labels  
0       setosa      0       0  
1       setosa      0       0  
2       setosa      0       0  
3       setosa      0       0  
4       setosa      0       0  
..         ...    ...     ...  
145  verginica      2       1  
146  verginica      2       1  
147  verginica      2       1  
148  verginica      2       1  
149  verginica      2       1  

[150 rows x 7 columns]

In [45]:
new_data = np.array([[5.111, 3.462, 1.41, 0.19], [6.2, 3.0, 5.4, 2.3]])
new_data = new_data.reshape(2, -1) # 모델과 데이터의 모양을 맞춰줘야 함
tree_model.predict(new_data)

array([0, 1])