In [15]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [16]:
MinMaxscaler = MinMaxScaler()
Standardscaler = StandardScaler()

In [17]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [18]:
MinMaxscaler.fit(xy)
Standardscaler.fit(xy)

StandardScaler()

In [20]:
MinMaxscaled_xy = MinMaxscaler.transform(xy)
Standardscaled_xy = Standardscaler.transform(xy)

In [21]:
MinMaxscaled_xy 

array([[1.        , 1.        , 0.        , 1.        , 1.        ],
       [0.70548491, 0.70439552, 1.        , 0.71881783, 0.83755792],
       [0.54412549, 0.50274824, 0.57608696, 0.60646801, 0.6606331 ],
       [0.33890353, 0.31368023, 0.10869565, 0.45989134, 0.43800918],
       [0.51436   , 0.4258239 , 0.30434783, 0.58504805, 0.42624401],
       [0.49556179, 0.4258239 , 0.31521739, 0.48131134, 0.49276137],
       [0.11436064, 0.        , 0.20652174, 0.22007776, 0.18597238],
       [0.        , 0.07747099, 0.5326087 , 0.        , 0.        ]])

In [22]:
Standardscaled_xy

array([[ 1.80044859,  1.88513361, -1.28230078,  1.72787156,  1.61889903],
       [ 0.81097514,  0.9053588 ,  2.08831842,  0.73846426,  1.08747361],
       [ 0.26886075,  0.23700312,  0.65946897,  0.34313432,  0.50866828],
       [-0.42061729, -0.38965881, -0.91592913, -0.17263101, -0.21964058],
       [ 0.16885854, -0.017961  , -0.25646016,  0.26776306, -0.25813006],
       [ 0.10570276, -0.017961  , -0.21982299, -0.0972596 , -0.04052009],
       [-1.17500725, -1.42934534, -0.58619464, -1.01647295, -1.04417298],
       [-1.55922124, -1.17256937,  0.51292031, -1.79086963, -1.65257721]])

In [8]:
xy = MinMaxscaled_xy

In [6]:
xy.shape

(8, 5)

In [9]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [10]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1]), name='weight') 
b = tf.Variable(tf.random_normal([1]), name='bias')

In [11]:
hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) 
train = optimizer.minimize(cost)

In [12]:
sess = tf.Session() 
sess.run(tf.global_variables_initializer()) 
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.03598339 
Prediction:
 [[0.8725163 ]
 [0.5686556 ]
 [0.5629356 ]
 [0.5818908 ]
 [0.56922054]
 [0.51557827]
 [0.38960508]
 [0.32654354]]
1 Cost:  0.035983242 
Prediction:
 [[0.87251693]
 [0.5686559 ]
 [0.56293565]
 [0.58189046]
 [0.56922054]
 [0.51557803]
 [0.3896044 ]
 [0.3265428 ]]
2 Cost:  0.035983086 
Prediction:
 [[0.8725176 ]
 [0.5686562 ]
 [0.5629357 ]
 [0.5818902 ]
 [0.5692204 ]
 [0.5155779 ]
 [0.38960367]
 [0.32654202]]
3 Cost:  0.035982937 
Prediction:
 [[0.8725182 ]
 [0.56865644]
 [0.56293565]
 [0.58188987]
 [0.5692203 ]
 [0.5155778 ]
 [0.389603  ]
 [0.32654124]]
4 Cost:  0.035982773 
Prediction:
 [[0.8725188 ]
 [0.5686568 ]
 [0.5629357 ]
 [0.58188957]
 [0.5692202 ]
 [0.5155776 ]
 [0.3896023 ]
 [0.32654047]]
5 Cost:  0.03598263 
Prediction:
 [[0.87251943]
 [0.56865704]
 [0.5629357 ]
 [0.5818893 ]
 [0.5692201 ]
 [0.51557755]
 [0.38960165]
 [0.32653973]]
6 Cost:  0.035982475 
Prediction:
 [[0.8725201 ]
 [0.5686574 ]
 [0.5629357 ]
 [0.5818889 ]
 [0.56922007]
 [0.51557

283 Cost:  0.035940167 
Prediction:
 [[0.8726934 ]
 [0.5687394 ]
 [0.5629386 ]
 [0.58180285]
 [0.56919676]
 [0.51553965]
 [0.38940993]
 [0.32632646]]
284 Cost:  0.035940006 
Prediction:
 [[0.872694  ]
 [0.5687398 ]
 [0.5629386 ]
 [0.5818025 ]
 [0.5691967 ]
 [0.5155394 ]
 [0.38940924]
 [0.32632568]]
285 Cost:  0.035939857 
Prediction:
 [[0.8726947 ]
 [0.56874   ]
 [0.56293863]
 [0.5818022 ]
 [0.5691966 ]
 [0.51553935]
 [0.38940853]
 [0.3263249 ]]
286 Cost:  0.03593971 
Prediction:
 [[0.8726953 ]
 [0.56874025]
 [0.5629386 ]
 [0.5818019 ]
 [0.56919646]
 [0.5155393 ]
 [0.38940787]
 [0.32632414]]
287 Cost:  0.03593954 
Prediction:
 [[0.8726959 ]
 [0.56874067]
 [0.5629387 ]
 [0.58180153]
 [0.56919634]
 [0.51553905]
 [0.38940716]
 [0.3263234 ]]
288 Cost:  0.03593939 
Prediction:
 [[0.8726965 ]
 [0.56874096]
 [0.5629387 ]
 [0.58180124]
 [0.5691963 ]
 [0.515539  ]
 [0.3894065 ]
 [0.32632262]]
289 Cost:  0.035939243 
Prediction:
 [[0.8726972 ]
 [0.5687412 ]
 [0.5629387 ]
 [0.58180094]
 [0.569196

483 Cost:  0.035909623 
Prediction:
 [[0.8728186 ]
 [0.5687987 ]
 [0.5629407 ]
 [0.5817406 ]
 [0.56917995]
 [0.51551235]
 [0.38927203]
 [0.326173  ]]
484 Cost:  0.035909474 
Prediction:
 [[0.8728192 ]
 [0.568799  ]
 [0.5629406 ]
 [0.58174026]
 [0.56917983]
 [0.5155122 ]
 [0.38927132]
 [0.32617223]]
485 Cost:  0.03590932 
Prediction:
 [[0.87281984]
 [0.5687993 ]
 [0.5629407 ]
 [0.58173996]
 [0.5691798 ]
 [0.5155121 ]
 [0.38927063]
 [0.3261715 ]]
486 Cost:  0.035909165 
Prediction:
 [[0.8728205 ]
 [0.5687996 ]
 [0.5629407 ]
 [0.58173966]
 [0.56917965]
 [0.515512  ]
 [0.38926995]
 [0.3261707 ]]
487 Cost:  0.035909012 
Prediction:
 [[0.8728211 ]
 [0.56879985]
 [0.5629408 ]
 [0.5817393 ]
 [0.56917953]
 [0.51551175]
 [0.38926926]
 [0.32616994]]
488 Cost:  0.035908863 
Prediction:
 [[0.8728217 ]
 [0.5688002 ]
 [0.5629407 ]
 [0.58173907]
 [0.56917953]
 [0.5155117 ]
 [0.38926858]
 [0.3261692 ]]
489 Cost:  0.035908714 
Prediction:
 [[0.87282234]
 [0.56880045]
 [0.5629408 ]
 [0.5817387 ]
 [0.5691

683 Cost:  0.035879105 
Prediction:
 [[0.87294376]
 [0.568858  ]
 [0.56294274]
 [0.5816784 ]
 [0.5691631 ]
 [0.51548505]
 [0.3891341 ]
 [0.3260196 ]]
684 Cost:  0.035878956 
Prediction:
 [[0.87294436]
 [0.56885827]
 [0.56294274]
 [0.5816781 ]
 [0.569163  ]
 [0.51548505]
 [0.38913342]
 [0.3260188 ]]
685 Cost:  0.035878804 
Prediction:
 [[0.872945  ]
 [0.56885856]
 [0.56294286]
 [0.5816778 ]
 [0.56916296]
 [0.5154848 ]
 [0.38913274]
 [0.32601804]]
686 Cost:  0.03587865 
Prediction:
 [[0.87294567]
 [0.56885886]
 [0.5629428 ]
 [0.5816775 ]
 [0.56916285]
 [0.5154847 ]
 [0.38913202]
 [0.3260173 ]]
687 Cost:  0.0358785 
Prediction:
 [[0.87294626]
 [0.5688591 ]
 [0.56294286]
 [0.5816772 ]
 [0.5691628 ]
 [0.5154846 ]
 [0.38913134]
 [0.32601652]]
688 Cost:  0.035878345 
Prediction:
 [[0.87294686]
 [0.56885946]
 [0.56294286]
 [0.58167684]
 [0.5691627 ]
 [0.51548445]
 [0.38913065]
 [0.32601574]]
689 Cost:  0.0358782 
Prediction:
 [[0.8729475 ]
 [0.56885976]
 [0.56294286]
 [0.58167654]
 [0.56916267

883 Cost:  0.03584861 
Prediction:
 [[0.8730689 ]
 [0.5689173 ]
 [0.5629449 ]
 [0.58161616]
 [0.56914634]
 [0.51545787]
 [0.38899618]
 [0.32586616]]
884 Cost:  0.035848465 
Prediction:
 [[0.8730695 ]
 [0.5689175 ]
 [0.5629449 ]
 [0.5816159 ]
 [0.5691463 ]
 [0.51545775]
 [0.3889955 ]
 [0.3258654 ]]
885 Cost:  0.03584831 
Prediction:
 [[0.8730702 ]
 [0.5689178 ]
 [0.5629449 ]
 [0.58161557]
 [0.56914616]
 [0.5154576 ]
 [0.3889948 ]
 [0.3258646 ]]
886 Cost:  0.035848152 
Prediction:
 [[0.87307084]
 [0.5689181 ]
 [0.5629449 ]
 [0.58161527]
 [0.56914604]
 [0.5154574 ]
 [0.38899413]
 [0.32586384]]
887 Cost:  0.035848014 
Prediction:
 [[0.87307143]
 [0.56891835]
 [0.5629449 ]
 [0.581615  ]
 [0.56914604]
 [0.5154573 ]
 [0.38899344]
 [0.3258631 ]]
888 Cost:  0.035847854 
Prediction:
 [[0.873072  ]
 [0.5689187 ]
 [0.5629449 ]
 [0.5816146 ]
 [0.5691459 ]
 [0.51545715]
 [0.38899276]
 [0.32586232]]
889 Cost:  0.0358477 
Prediction:
 [[0.8730727 ]
 [0.568919  ]
 [0.56294495]
 [0.5816144 ]
 [0.5691458

 [0.3257135 ]]
1083 Cost:  0.03581813 
Prediction:
 [[0.8731941 ]
 [0.5689765 ]
 [0.5629469 ]
 [0.58155406]
 [0.5691295 ]
 [0.51543057]
 [0.38885826]
 [0.32571274]]
1084 Cost:  0.035817984 
Prediction:
 [[0.8731947 ]
 [0.56897676]
 [0.562947  ]
 [0.5815537 ]
 [0.5691294 ]
 [0.51543045]
 [0.3888576 ]
 [0.32571197]]
1085 Cost:  0.035817824 
Prediction:
 [[0.87319535]
 [0.56897706]
 [0.56294703]
 [0.5815534 ]
 [0.56912935]
 [0.51543033]
 [0.3888569 ]
 [0.3257112 ]]
1086 Cost:  0.035817675 
Prediction:
 [[0.873196  ]
 [0.56897736]
 [0.5629469 ]
 [0.5815531 ]
 [0.5691293 ]
 [0.51543015]
 [0.38885623]
 [0.32571042]]
1087 Cost:  0.03581752 
Prediction:
 [[0.8731966 ]
 [0.56897765]
 [0.562947  ]
 [0.58155274]
 [0.5691291 ]
 [0.5154301 ]
 [0.38885552]
 [0.32570964]]
1088 Cost:  0.03581737 
Prediction:
 [[0.8731972 ]
 [0.56897795]
 [0.56294703]
 [0.5815525 ]
 [0.5691291 ]
 [0.5154299 ]
 [0.38885483]
 [0.3257089 ]]
1089 Cost:  0.035817217 
Prediction:
 [[0.87319785]
 [0.56897825]
 [0.562947  ]
 [

1276 Cost:  0.035788737 
Prediction:
 [[0.87331486]
 [0.5690336 ]
 [0.56294894]
 [0.581494  ]
 [0.5691133 ]
 [0.51540434]
 [0.38872522]
 [0.32556465]]
1277 Cost:  0.035788585 
Prediction:
 [[0.8733155 ]
 [0.5690339 ]
 [0.562949  ]
 [0.5814937 ]
 [0.56911325]
 [0.51540416]
 [0.3887245 ]
 [0.3255639 ]]
1278 Cost:  0.03578843 
Prediction:
 [[0.87331617]
 [0.5690342 ]
 [0.56294894]
 [0.5814934 ]
 [0.56911314]
 [0.515404  ]
 [0.38872382]
 [0.32556313]]
1279 Cost:  0.03578828 
Prediction:
 [[0.87331676]
 [0.5690345 ]
 [0.562949  ]
 [0.5814931 ]
 [0.569113  ]
 [0.51540387]
 [0.38872313]
 [0.32556236]]
1280 Cost:  0.03578812 
Prediction:
 [[0.87331736]
 [0.56903493]
 [0.56294906]
 [0.5814928 ]
 [0.569113  ]
 [0.51540375]
 [0.38872242]
 [0.32556158]]
1281 Cost:  0.03578797 
Prediction:
 [[0.873318  ]
 [0.5690352 ]
 [0.56294894]
 [0.5814924 ]
 [0.5691129 ]
 [0.5154035 ]
 [0.38872176]
 [0.32556084]]
1282 Cost:  0.03578782 
Prediction:
 [[0.8733187 ]
 [0.5690354 ]
 [0.56294906]
 [0.5814921 ]
 [0.5

1460 Cost:  0.035760727 
Prediction:
 [[0.87343   ]
 [0.5690881 ]
 [0.56295085]
 [0.58143675]
 [0.5690978 ]
 [0.5153792 ]
 [0.38859832]
 [0.3254235 ]]
1461 Cost:  0.03576056 
Prediction:
 [[0.87343067]
 [0.5690885 ]
 [0.56295097]
 [0.5814364 ]
 [0.56909776]
 [0.5153791 ]
 [0.38859764]
 [0.32542273]]
1462 Cost:  0.035760414 
Prediction:
 [[0.8734313 ]
 [0.5690888 ]
 [0.5629509 ]
 [0.58143616]
 [0.56909764]
 [0.51537895]
 [0.38859695]
 [0.325422  ]]
1463 Cost:  0.035760265 
Prediction:
 [[0.8734319 ]
 [0.569089  ]
 [0.56295097]
 [0.5814358 ]
 [0.5690976 ]
 [0.51537883]
 [0.38859624]
 [0.3254212 ]]
1464 Cost:  0.03576011 
Prediction:
 [[0.8734325 ]
 [0.5690894 ]
 [0.56295097]
 [0.58143556]
 [0.5690975 ]
 [0.5153787 ]
 [0.38859555]
 [0.32542044]]
1465 Cost:  0.035759952 
Prediction:
 [[0.8734332 ]
 [0.5690897 ]
 [0.56295097]
 [0.5814352 ]
 [0.5690974 ]
 [0.51537853]
 [0.38859487]
 [0.32541966]]
1466 Cost:  0.035759807 
Prediction:
 [[0.8734338 ]
 [0.5690899 ]
 [0.56295097]
 [0.5814349 ]
 [

1630 Cost:  0.035734847 
Prediction:
 [[0.87353647]
 [0.5691385 ]
 [0.56295276]
 [0.5813839 ]
 [0.5690836 ]
 [0.515356  ]
 [0.38848108]
 [0.3252931 ]]
1631 Cost:  0.0357347 
Prediction:
 [[0.87353706]
 [0.5691388 ]
 [0.56295264]
 [0.5813836 ]
 [0.56908345]
 [0.51535594]
 [0.3884804 ]
 [0.32529232]]
1632 Cost:  0.03573454 
Prediction:
 [[0.87353766]
 [0.5691391 ]
 [0.5629527 ]
 [0.5813833 ]
 [0.56908333]
 [0.51535577]
 [0.3884797 ]
 [0.32529154]]
1633 Cost:  0.035734396 
Prediction:
 [[0.8735383 ]
 [0.5691394 ]
 [0.56295276]
 [0.581383  ]
 [0.56908333]
 [0.51535565]
 [0.38847905]
 [0.3252908 ]]
1634 Cost:  0.03573424 
Prediction:
 [[0.873539  ]
 [0.5691397 ]
 [0.5629527 ]
 [0.58138263]
 [0.5690832 ]
 [0.51535547]
 [0.38847834]
 [0.32529002]]
1635 Cost:  0.035734087 
Prediction:
 [[0.87353957]
 [0.56914   ]
 [0.56295276]
 [0.5813824 ]
 [0.5690831 ]
 [0.51535535]
 [0.38847765]
 [0.32528925]]
1636 Cost:  0.035733934 
Prediction:
 [[0.87354016]
 [0.5691403 ]
 [0.56295276]
 [0.58138204]
 [0.

1882 Cost:  0.035696514 
Prediction:
 [[0.8736942 ]
 [0.5692133 ]
 [0.5629554 ]
 [0.58130556]
 [0.56906235]
 [0.5153217 ]
 [0.38830733]
 [0.32509977]]
1883 Cost:  0.035696365 
Prediction:
 [[0.8736948 ]
 [0.5692135 ]
 [0.5629553 ]
 [0.5813052 ]
 [0.56906223]
 [0.5153215 ]
 [0.38830662]
 [0.325099  ]]
1884 Cost:  0.035696216 
Prediction:
 [[0.8736954 ]
 [0.56921387]
 [0.5629553 ]
 [0.5813049 ]
 [0.5690622 ]
 [0.5153215 ]
 [0.38830596]
 [0.32509822]]
1885 Cost:  0.03569606 
Prediction:
 [[0.873696  ]
 [0.56921417]
 [0.5629554 ]
 [0.58130455]
 [0.5690621 ]
 [0.51532125]
 [0.38830528]
 [0.32509747]]
1886 Cost:  0.035695918 
Prediction:
 [[0.8736967 ]
 [0.56921434]
 [0.5629553 ]
 [0.5813043 ]
 [0.569062  ]
 [0.51532114]
 [0.3883046 ]
 [0.3250967 ]]
1887 Cost:  0.035695758 
Prediction:
 [[0.8736973 ]
 [0.5692147 ]
 [0.5629554 ]
 [0.58130395]
 [0.5690619 ]
 [0.515321  ]
 [0.38830388]
 [0.32509592]]
1888 Cost:  0.03569561 
Prediction:
 [[0.8736979 ]
 [0.56921506]
 [0.5629554 ]
 [0.5813037 ]
 [